--Account table
DROP TABLE IF EXISTS league.RiotAccount;
CREATE TABLE RiotAccount (
    Id bigint PRIMARY KEY generated always as identity,
    Puuid VARCHAR(255),
    GameName VARCHAR(255),
    TagLine VARCHAR(255)
);

--MetadataDto and InfoDtos
CREATE TABLE Match (
    Id bigint PRIMARY KEY generated always as identity,
    MatchId VARCHAR(255)
    DataVersion VARCHAR(255),
    EndOfGameResult VARCHAR(255),
    GameCreation bigint,
    GameDuration bigint,
    GameEndTimestamp bigint,
    GameId bigint,
    GameMode VARCHAR(255),
    GameStartTimestamp bigint,
    GameType VARCHAR(255),
    GameVersion VARCHAR(255),
    MapId int,
    PlatformId VARCHAR(255),
    QueueId int,
    --LINK table for teams
    TournamentCode VARCHAR(255)
);

--everyone who played in the match
--might be able to link participants too
CREATE TABLE RiotAccountToMatch (
    Id bigint PRIMARY KEY generated always as identity,
    RiotAccountId bigint, --TODO foreign key
    MatchId bigint, --TODO foreign
    ParticipantId bigint --TODO foreign key
);

CREATE TABLE Participants (
    Id bigint PRIMARY KEY generated always as identity,
    AllInPings int,
    AssistMePings int,
    Assists int,
    BaronKills int,
    BountyLevel int,
    ChampExperience int,
    ChampLevel int,
    ChampionId int
    ChampionName VARCHAR(255),
    CommandPings int,
    ChampionTransform int,
    ConsumablesPurchased int
    --LINK table for challenges
    DamageDealtToBuildings int,
    DamageDealtToObjectives int,
    DamageDealtToTurrets int,
    DamageSelfMitigated int,
    Deaths int,
    DetectorWardsPlaced int,
    DoubleKills int,
    DragonKills int,
    EligibleForProgression boolean,
    EnemyMissingPings int,
    EnemyVisionPings int,
    FirstBloodAssist boolean,
    FirstBloodKill boolean,
    FirstTowerAssist boolean,
    FirstTowerKill boolean,
    GameEndedInEarlySurrender boolean,
    GameEndedInSurrender boolean,
    HoldPings int,
    GetBackPings int,
    GoldEarned int,
    GoldSpent int,
    IndividualPosition VARCHAR(255),
    InhibitorKills int,
    InhibitorTakedowns int,
    InhibitorsLost int,
    Item0 int,
    Item1 int,
    Item2 int,
    Item3 int,
    Item4 int,
    Item5 int,
    Item6 int,
    ItemsPurchased int,
    KillingSprees int,
    Kills int,
    Lane VARCHAR(255),
    LargestCriticalStrike int,
    LargestKillingSpree int,
    LargestMultiKill int,
    LongestTimeSpentLiving int,
    MagicDamageDealt int,
    MagicDamageDealtToChampions int,
    MagicDamageTaken int,
    --LINK table for missions
    NeutralMinionsKilled int,
    NeedVisionPings int,
    NexusKills int,
    NexusTakedowns int,
    NexusLost int,
    ObjectivesStolen int,
    ObjectivesStolenAssists int,
    OnMyWayPings int,
    ParticipantId int,
    PlayerScore0 int,
    PlayerScore1 int,
    PlayerScore2 int,
    PlayerScore3 int,
    PlayerScore4 int,
    PlayerScore5 int,
    PlayerScore6 int,
    PlayerScore7 int,
    PlayerScore8 int,
    PlayerScore9 int,
    PlayerScore10 int,
    PlayerScore11 int,
    PentaKills int,
    --LINK table for perks
    PhysicalDamageDealt int,
    PhysicalDamageDealtToChampions int,
    PhysicalDamageTaken int,
    Placement int,
    PlayerAugment1 int,
    PlayerAugment2 int,
    PlayerAugment3 int,
    PlayerAugment4 int,
    PlayerSubteamId int,
    PushPings int,
    ProfileIcon int,
    Puuid VARCHAR(255),
    QuadraKills int,
    RiotIdGameName VARCHAR(255),
    RiotIdName VARCHAR(255),
    RiotIdTagline VARCHAR(255),
    GameRole varchar(255),
    SightWardsBoughtInGame int,
    Spell1Casts int,
    Spell2Casts int,
    Spell3Casts int,
    Spell4Casts int,
    SubteamPlacement int,
    Summoner1Casts int,
    Summoner1Id int,
    Summoner2Casts int,
    Summoner2Id int,
    SummonerId varchar(255),
    SummonerLevel int,
    SummonerName varchar(255),
    TeamEarlySurrendered boolean,
    TeamId int,
    TeamPosition varchar(255),
    TimeCCingOthers int,
    TimePlayed int,
    TotalAllyJungleMinionsKilled int,
    TotalDamageDealt int,
    TotalDamageDealtToChampions int,
    TotalDamageShieldedOnTeammates int,
    TotalDamageTaken int,
    TotalEnemyJungleMinionsKilled int,
    TotalHeal int,
    TotalHealsOnTeammates int,
    TotalMinionsKilled int,
    TotalTimeCCDealt int,
    TotalTimeSpentDead int,
    TotalUnitsHealed int,
    TripleKills int,
    TrueDamageDealt int,
    TrueDamageDealtToChampions int,
    TrueDamageTaken int,
    TurretKills int,
    TurretTakedowns int,
    TurretsLost int,
    UnrealKills int,
    VisionScore int,
    VisionClearedPings int,
    VisionWardsBoughtInGame int,
    WardsKilled int,
    WardsPlaced int,
    Win boolean

);

--

 --1-1
 --1-many
 --many-1
 --many-many